# Generated by Django 4.1.5 on 2023-01-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_chapter_remove_project_image_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_good', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category', verbose_name='cat')),
                ('name_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.good', verbose_name='good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.order', verbose_name='order')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcat', models.CharField(max_length=250)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category', verbose_name='category')),
            ],
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='name',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.subcategory', verbose_name='subcat'),
        ),
        migrations.AddField(
            model_name='good',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.subcategory', verbose_name='subcategory'),
        ),
        migrations.AddField(
            model_name='allowedcombination',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.category'),
        ),
        migrations.AddField(
            model_name='allowedcombination',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.good'),
        ),
        migrations.AddField(
            model_name='allowedcombination',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.subcategory'),
        ),
    ]
