# Generated by Django 4.1.5 on 2023-01-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_allowedcombination_category_good_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name_good',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subcat',
        ),
        migrations.DeleteModel(
            name='AllowedCombination',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
