# Generated by Django 4.1.5 on 2023-01-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
