# Generated by Django 4.1.5 on 2023-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_generalmenu_generalmenuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalmenu',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='generalmenu',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='generalmenu',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='generalmenu',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='generalmenuitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='generalmenuitem',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='generalmenuitem',
            name='quantity',
        ),
    ]
