# Generated by Django 4.1.5 on 2023-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_remove_generalmenu_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmenu',
            name='id_cat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
