# Generated by Django 4.1.5 on 2023-01-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_subcategory_id_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='id_subcat',
        ),
    ]
