# Generated by Django 4.1.5 on 2023-01-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_subcategory_id_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='id_subcat',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
